[project]
name = "blender-asset-tracer"
version = "2.0.0b0"
description = "Better version of BAT"
authors = [{ name = "Sybren A. Stüvel", email = "sybren@blender.org" }]
requires-python = "==3.13.*"
license = "GPL-3.0-or-later"
dependencies = [
    # Tracks Blender's bundled version.
    "cattrs==25.1.1",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1,<2",
    "ruff>=0.15.0,<0.16",
]
release = [
    "twine>=6.2.0",
]

[tool.setuptools]
packages = ["blender_asset_tracer"]

[tool.uv]
# Don't install the 'release' group by default. That pulls in Twine and its
# dependencies, which are only interesting for people who need to publish
# release packages.
default-groups = ["dev"]

[[tool.uv.index]]
name = "michaelgold"
url = "https://michaelgold.github.io/buildbpy/"

[tool.mypy]
# Prevent error message that bpy is untyped (most of its code is, indeed, untyped).
disable_error_code = "import-untyped"
files = ["."]
# Ignore files in directories with ___ in their name. This is just a way to hide
# things from mypy.
exclude = "___|^docs/|/2D_Animation"
strict = true

[[tool.mypy.overrides]]
# Mypy doesn't like our use of mypy.api for some reason.
module = "run_mypy"
ignore_errors = true

[tool.ruff]
line-length = 88
target-version = "py313"

# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
lint.select = ["E4", "E7", "E9", "F", "W", "C901"]
lint.ignore = [
# Import not at top of file. BAT needs to add to sys.path before importing.
"E402"
]

# Allow fix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]
lint.unfixable = []
